<?php namespace ProcessWire;

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load composer's autoloader
require __DIR__ . DIRECTORY_SEPARATOR . "vendor/autoload.php";

/**
 * Class WirePHPMailer
 *
 * @author			: İskender TOTOĞLU, @ukyo (community), @trk (Github)
 * @website			: https://www.altivebir.com
 * @projectWebsite	: https://github.com/trk/WirePHPMailer
 */
class WirePHPMailer extends WireData implements Module, ConfigurableModule {

    /**
     * PHPMailer Version
     */
    const PHPMailer_VERSION = "6.0.3";

    /**
     * PHPMailer instance
     *
     * @var PHPMailer
     */
    protected $PHPMailer;

    public $configs = array();
    public $defaults = array();

    // ------------------------------------------------------------------------

    /**
     * Module info
     *
     * @see Module
     * @return array
     */
    public static function getModuleInfo() {
        return array(
            "title" => "WirePHPMailer",
            "version" => 1,
            "summary" => __("This module integrating the PHPMailer mailing library into ProcessWire."),
            "href" => "https://github.com/trk/WirePHPMailer",
            "author" => "İskender TOTOĞLU | @ukyo(community), @trk (Github), https://www.altivebir.com",
            "autoload" => false, //
            // "permanent" => false,
            "requires" => array(
                "PHP>=7.0.0",
                "ProcessWire>=3.0.0",
                "InputfieldHelper"
            ),
            "installs" => array(),
            // "permanent" => false
            // "permission" => "permission-name",
            // "permissions" => array()
            "icon" => "envelope-o",
            // "singular" => false,
            // "autoload" => false
        );
    }

    // ------------------------------------------------------------------------

    /**
     * Populate the default config data
     *
     * WireMailPHPMailer constructor.
     */
    public function __construct() {
        $InputfieldHelper = $this->modules->get("InputfieldHelper");
        if($InputfieldHelper) {
            $this->configs = $InputfieldHelper->getModuleConfigs($this->className);
            $this->defaults = $InputfieldHelper->getDefaults($this->configs);
            foreach($this->defaults as $key => $value) {
                $this->$key = $value;
            }
        }
    }

    // ------------------------------------------------------------------------

    /**
     * Initialize the module
     */
    public function init() {
        $this->PHPMailer = new PHPMailer();
        foreach($this->defaults as $key => $value) {
            $this->PHPMailer->{$key} = $this->{$key};
        }
        return $this->PHPMailer;
    }

    // ------------------------------------------------------------------------

    /**
     * Return PHPMailer instance
     *
     * @return PHPMailer
     */
    public function mailer() { return $this->PHPMailer; }

    // ------------------------------------------------------------------------

    /**
     * Module configuration
     *
     * @param array $data
     * @return null|InputfieldWrapper
     * @throws WireException
     * @throws WirePermissionException
     */
    public function getModuleConfigInputfields(array $data) {
        $InputfieldHelper = $this->modules->get("InputfieldHelper");
        return $InputfieldHelper->buildInputfields($this->configs, null, array_merge($this->defaults, $data));
    }
}